export const ERROR_CODES = {
  CHROME_NOT_FOUND: "CHROME_NOT_FOUND",
  LOGIN_REQUIRED: "LOGIN_REQUIRED",
  ANTI_BOT_CHALLENGE: "ANTI_BOT_CHALLENGE",
  OZON_SKU_NOT_FOUND: "OZON_SKU_NOT_FOUND",
  FULL_CROP_NOT_APPLIED: "FULL_CROP_NOT_APPLIED",
  IMAGE_SEARCH_NOT_ENTERED_RESULT_PAGE: "IMAGE_SEARCH_NOT_ENTERED_RESULT_PAGE",
  UNKNOWN: "UNKNOWN",
} as const;

export type SidecarErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
